// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqMmpve4KIeW6ojgaZh3jek6rqHCF9B4',
    appId: '1:897050920243:web:fb65fdde113323a7726a46',
    messagingSenderId: '897050920243',
    projectId: 'sample-project-1c5a1',
    authDomain: 'sample-project-1c5a1.firebaseapp.com',
    databaseURL: 'https://sample-project-1c5a1-default-rtdb.firebaseio.com',
    storageBucket: 'sample-project-1c5a1.firebasestorage.app',
    measurementId: 'G-C2K69XGNZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbLpQSmG0BEW5eJlmxx01w69iONJs1A1w',
    appId: '1:897050920243:android:679ac7bd0a6e7f3e726a46',
    messagingSenderId: '897050920243',
    projectId: 'sample-project-1c5a1',
    databaseURL: 'https://sample-project-1c5a1-default-rtdb.firebaseio.com',
    storageBucket: 'sample-project-1c5a1.firebasestorage.app',
  );

}